import { Rubik } from "next/font/google";
import "./globals.css";
import Header from '../components/layout/header';

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type RootLayoutProps = {
  children: React.ReactNode;
};
export default function RootLayout({ children }:RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} antialiased`}
      >
      <Header />
        {children}
      </body>
    </html>
  );
}
 